export const data = [
  {
    id: 1,
    name: "Project A",
    client: "Client 1",
    assigned: "John Doe",
    dueDate: "2023-04-30",
    status: 1,
  },
  {
    id: 2,
    name: "Project B",
    client: "Client 2",
    assigned: "Jane Smith",
    dueDate: "2023-05-15",
    status: 1,
  },
  {
    id: 3,
    name: "Project C",
    client: "Client 3",
    assigned: "John Doe",
    dueDate: "2023-06-10",
    status: 0,
  },
  {
    id: 4,
    name: "Project D",
    client: "Client 1",
    assigned: "Jane Smith",
    dueDate: "2023-05-01",
    status: 1,
  },
  {
    id: 5,
    name: "Project E",
    client: "Client 4",
    assigned: "John Doe",
    dueDate: "2023-07-20",
    status: 0,
  },
  {
    id: 6,
    name: "Project A",
    client: "Client 1",
    assigned: "John Doe",
    dueDate: "2023-04-30",
    status: 1,
  },
  {
    id: 7,
    name: "Project B",
    client: "Client 2",
    assigned: "Jane Smith",
    dueDate: "2023-05-15",
    status: 1,
  },
  {
    id: 8,
    name: "Project C",
    client: "Client 3",
    assigned: "John Doe",
    dueDate: "2023-06-10",
    status: 0,
  },
  {
    id: 9,
    name: "Project D",
    client: "Client 1",
    assigned: "Jane Smith",
    dueDate: "2023-05-01",
    status: 1,
  },
  {
    id: 10,
    name: "Project E",
    client: "Client 4",
    assigned: "John Doe",
    dueDate: "2023-07-20",
    status: 0,
  },
  {
    id: 11,
    name: "Project A",
    client: "Client 1",
    assigned: "John Doe",
    dueDate: "2023-04-30",
    status: 1,
  },
  {
    id: 12,
    name: "Project B",
    client: "Client 2",
    assigned: "Jane Smith",
    dueDate: "2023-05-15",
    status: 1,
  },
  {
    id: 13,
    name: "Project C",
    client: "Client 3",
    assigned: "John Doe",
    dueDate: "2023-06-10",
    status: 0,
  },
  {
    id: 14,
    name: "Project D",
    client: "Client 1",
    assigned: "Jane Smith",
    dueDate: "2023-05-01",
    status: 1,
  },
  {
    id: 15,
    name: "Project E",
    client: "Client 4",
    assigned: "John Doe",
    dueDate: "2023-07-20",
    status: 0,
  },
];
